export const LOAD_INGREDIENTS_SUCCESS = "LOAD_INGREDIENTS_SUCCESS";
export const ADD_INGREDIENTS_SUCCESS = "ADD_INGREDIENTS_SUCCESS";
export const REMOVE_INGREDIETNS_SUCCESS = "REMOVE_INGREDIETNS_SUCCESS";
export const GET_ALL_INGREDIETNS_SUCCESS = "GET_ALL_INGREDIETNS_SUCCESS";
