export const LOAD_INGREDIENTS_SUCCESS = "LOAD_INGREDIENTS_SUCCESS";
export const ADD_INGREDIENTS_SUCCESS = "ADD_INGREDIENTS_SUCCESS";
export const REMOVE_INGREDIETNS_SUCCESS = "REMOVE_INGREDIETNS_SUCCESS";
export const GET_ALL_INGREDIETNS_SUCCESS = "GET_ALL_INGREDIETNS_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_START_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH_START_FAILED = "AUTH_START_FAILED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const BUGER_BUILDING = "BUGER_BUILDING";
export const BUGER_BUILDING_FINISHED = "BUGER_BUILDING_FINISHED";
